try:
   raise ValueError
except ValueError:
   print("Exception ValueError !")
   
